#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] ||= File.join(__dir__, "Gemfile")
require "bundler/setup"

require 'net/http'
require 'uri'
require 'json'
require 'fileutils'
require 'exif'
require 'optparse'

require_relative 'lib/google_photos/auth'
require_relative 'lib/google_photos/client'
require_relative 'lib/cli/commands/import'

CACHE_PATH = "tmp"

# Parse command line options
options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} --album ALBUM_NAME"
  opts.on("--album ALBUM_NAME", "Name or ID of Flickr album to import") do |album|
    options[:album] = album
  end
end.parse!

if options[:album].nil?
  puts "Error: --album option is required"
  exit 1
end

# Load Flickr Albums
flickr_albums = JSON.parse(File.read('flickr/albums.json'))
album = flickr_albums['albums'].find { |a| [a['title'], a['id']].include?(options[:album]) }

if album.nil?
  puts "Error: Album '#{options[:album]}' not found"
  exit 1
end

album_title = album["title"]
album_description = (album["description"] || "").gsub(/<\/?b>/, '')

# Ensure cache exists
FileUtils.mkdir_p("#{CACHE_PATH}/#{album["id"]}")

photos = album["photos"].map do |photo_id|
  # Not sure why this happens sometimes
  next if photo_id == "0"

  {
    "id" => photo_id,
  }
end.compact

# Load configuration
config = JSON.parse(File.read('config.json'))
credentials = GooglePhotos::Auth.new(
  config['clientId'],
  config['clientSecret'],
).authorize

client = GooglePhotosClient.new(credentials)

puts "Uploading album: #{album["title"]}"
puts "Caching #{photos.count} photos locally..."

photos.each do |photo|
  photo_id = photo["id"]

  photo_json = JSON.parse(File.read("flickr/photo_#{photo_id}.json"))
  if (description = photo_json["description"])
    photo["description"] = description
  end

  photo_url = photo_json["original"]
  photo["url"] = photo_url

  ext = File.extname(photo_url)
  photo_file = "#{CACHE_PATH}/#{album["id"]}/#{photo_json["name"]}#{ext}"
  photo["path"] = photo_file
end

photos.sort_by! { |p| p["path"] }

photos.each do |photo|
  photo_url = photo["url"]
  photo_file = photo["path"]

  unless File.exist?(photo_file)
    puts "Downloading #{File.basename(photo_file)} (#{photo_url})"
    File.open(photo_file, 'wb') do |file|
      file.write(Net::HTTP.get(URI(photo_url)))
    end
  end
end

photos.each do |photo|
  photo_file = photo["path"]

  File.open(photo_file) do |f|
    exif = Exif::Data.new(f)
    puts "* #{photo_file} taken #{exif.date_time_original} - #{photo["description"]}"
  end
end

puts "Files ready to upload, continue? (y/n)"
continue = gets.chomp
if continue != "y"
  puts "Exiting..."
  exit
end

result = Flicker2GooglePhotos::Import.new(
  client:,
  photos:,
  album_title:,
  album_description:
).execute

puts "\n" + "="*60
puts "SUCCESS!"
puts "="*60
puts "Album ID: #{result[:album]['id']}"
puts "Album Title: #{result[:album]['title']}"
puts "Photos uploaded: #{result[:media_items].count}"
result[:media_items].each_with_index do |item, idx|
  puts "  #{idx + 1}. #{item['filename']} (ID: #{item['id']})"
end

config['importedAlbums'] ||= []
config['importedAlbums'] << {
  "title" => album_title,
  "flickrId" => album["id"],
  "googlePhotosId" => result[:album]["id"]
}

json = JSON.pretty_generate(config)
File.write('config.json', json)
